-- Add storage system fields to packages table
ALTER TABLE packages ADD COLUMN IF NOT EXISTS "storageDaysUsed" INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE packages ADD COLUMN IF NOT EXISTS "storageFeesPaid" BOOLEAN DEFAULT false NOT NULL;
ALTER TABLE packages ADD COLUMN IF NOT EXISTS "storageFeesAmount" INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE packages ADD COLUMN IF NOT EXISTS "lastStorageFeeCheck" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL;
